FUNCTION CAJA_UNI(NOMCAJ,UNICAJ,NIVEL2)
**1-cajas
**2-unidades por caja
**3-precio por unidad o caja
NIVEL2:=IF(NIVEL2=NIL,1,NIVEL2)
DO CASE
CASE NIVEL2<=2
   NIVEL2:=IF(NIVEL2=NIL, 1 ,NIVEL2)
   IF RAT("x",NOMCAJ)=29 .OR. RAT("/",NOMCAJ)=29
      IF RAT("x",NOMCAJ)=29
         NUMCAJ1:=RAT("x",NOMCAJ)
         NUMCAJ2:=RAT("x",NOMCAJ)-1
      ELSE //RAT("/",NOMCAJ)=29
         NUMCAJ1:=RAT("/",NOMCAJ)
         NUMCAJ2:=RAT("/",NOMCAJ)-1
      ENDIF
      DO WHILE ASC(SUBSTR(NOMCAJ,NUMCAJ2,1))>=48 .AND. ;
               ASC(SUBSTR(NOMCAJ,NUMCAJ2,1))<=57 .AND. NUMCAJ2>1
         NUMCAJ2--
      ENDDO
      NUMCAJ2++
      NUMCAJ1:=VAL(SUBSTR(NOMCAJ,NUMCAJ2,NUMCAJ1-NUMCAJ2))
      IF RAT("x",NOMCAJ)=29
         NUMCAJ3:=UNICAJ/NUMCAJ1
      ELSE //RAT("/",NOMCAJ)=29
         NUMCAJ3:=UNICAJ*NUMCAJ1
      ENDIF
   ELSE
      NUMCAJ1:=0
      NUMCAJ3:=0
   ENDIF
   IF NIVEL2=2 //UNIDADES UNA CAJA
      RETURN(NUMCAJ1)
   ELSE
      RETURN(NUMCAJ3)
   ENDIF
CASE NIVEL2=3
   IF SUBSTR(NOMCAJ,29,1)="/"
      NUMCAJ1:=2
   ELSE
      NUMCAJ1:=1
   ENDIF
   RETURN(NUMCAJ1)
ENDCASE
*
*
FUNCTION CAJA_MIL(NOMCAJ,UNICAJ,LARCAJ)
   NUMCAJ1:=CAJA_UNI(NOMCAJ,UNICAJ)
   DO CASE
   CASE NUMCAJ1=INT(NUMCAJ1) .AND. NUMCAJ1<>0
      UNICAJ:=MIL(NUMCAJ1,LARCAJ,0)
   CASE NUMCAJ1<>INT(NUMCAJ1) .AND. NUMCAJ1<>0
      UNICAJ:=MIL(NUMCAJ1,LARCAJ,2)
   OTHERWISE
      UNICAJ:=SPACE(LARCAJ)
   ENDCASE
   RETURN(UNICAJ)
*
*
FUNCTION KILOS(NOMKILO)
   NOMKILO:=UPPER(RTRIM(NOMKILO))
   DO CASE
   CASE NOMKILO=".KILOS="
      NOMKILO:=SUBSTR(NOMKILO,8,LEN(NOMKILO))
   CASE NOMKILO=".METROS="
      NOMKILO:=SUBSTR(NOMKILO,9,LEN(NOMKILO))
   CASE NOMKILO=".LITROS="
      NOMKILO:=SUBSTR(NOMKILO,9,LEN(NOMKILO))
   OTHERWISE
      RETURN(0)
   ENDCASE
   NUMKILO:=0
   NOMKILO:=STRTRAN(NOMKILO,",",".")
   DO WHILE LEN(NOMKILO)>0
      SUMKILO:=IF(NOMKILO="-","-","+")
      IF NOMKILO="+" .OR. NOMKILO="-"
         NOMKILO:=SUBSTR(NOMKILO,2,LEN(NOMKILO))
      ENDIF
      BUSKILO:=MIN(AT("+",NOMKILO),AT("-",NOMKILO))
      IF BUSKILO=0
         BUSKILO:=MAX(AT("+",NOMKILO),AT("-",NOMKILO))
      ENDIF
      IF BUSKILO=0
         BUSKILO:=LEN(NOMKILO)+1
      ENDIF
      IF SUMKILO="+"
         NUMKILO:=NUMKILO+VAL(SUBSTR(NOMKILO,1,BUSKILO-1))
      ELSE
         NUMKILO:=NUMKILO-VAL(SUBSTR(NOMKILO,1,BUSKILO-1))
      ENDIF
      NOMKILO:=SUBSTR(NOMKILO,BUSKILO,LEN(NOMKILO))
   ENDDO
   RETURN(NUMKILO)
*
*
