FUNCTION EMPRESA()
   LOCAL FNOM2:=NOMPROG()
   @ 0,0 SAY SPACE(80) COLOR COLORCAB
   @ 0,1 SAY FNOM2 COLOR COLORCAB
   IF NUMEMP<>0
      FNOM2:=LTRIM(STR(NUMEMP))+"-"
   ELSE
      FNOM2:=""
   ENDIF
   FNOM2:=FNOM2+RTRIM(EMPRESA)
   @ 0,20+INT((40-LEN(FNOM2))/2) SAY FNOM2 COLOR COLORGET2
   IF YEAR(DATE())<>EJERANY .AND. EJERANY<>0
      @ 0,COL()-4 SAY EJERANY COLOR COLORGET2+"*"
   ENDIF
   IF READINSERT()
      @ 0,64 SAY "Ins" COLOR COLORCAB
   ENDIF
   @ 0,68 SAY DIA(DATE(),11) COLOR COLORCAB
*
FUNCTION IMP_EMP(PAG,FECLIS)
   IF VALTYPE(FECLIS)<>"D"
      FECLIS:=DATE()
   ENDIF
   IF PAG<>1
      ?
   ENDIF
   ?? &LET_NOR
   IF AT("SUIZO.TEY",UPPER(RUTASUIZO))=0  .OR. ; //NO LISTAR EL NOMBRE DEL PROGRAMA
      AT("SUIZOWIN.TEY",UPPER(RUTAPROGRAMA))=0   //NO LISTAR EL NOMBRE DEL PROGRAMA
      ?? SPACE(IMP_ESPIZQ)
      ?? NOMPROG()
   ENDIF

   ? SPACE(IMP_ESPIZQ)
   ?? DIA(FECLIS,11)
   ?? SPACE((IF(IMP_NUM=5,72,58)-LEN(EMPRESA))/2)
   ?? EMPRESA
   ?? SPACE((IF(IMP_NUM=5,72,58)-LEN(EMPRESA))/2)
   ?? "HOJA: "+LTRIM(STR(PAG))
   RETURN
*
FUNCTION PROGRAMA2(FPRO2)
   LOCAL FNUM2:=0,FNOM2:=""
   FPRO2:=IF(FPRO2=NIL," ",FPRO2)

   DO WHILE !(PROCNAME(FNUM2)=="")
      FNOM2:=PROCNAME(FNUM2)
      IF FNOM2==(FPRO2) .AND. LEN(FPRO2)>1
         RETURN .T.
      ENDIF
      FNUM2++
      IF PROCNAME(FNUM2)=="MAIN" .AND. FPRO2==" "
         EXIT
      ENDIF
   ENDDO
   IF LEN(FPRO2)>1
      RETURN .F.
   ELSE
      RETURN(FNOM2)
   ENDIF
*
FUNCTION NOMPROG(LLAMADA) //VERSION,NOMBRE
   LLAMADA:=IF(LLAMADA=NIL,"VERSION",LLAMADA)
   FNOM2:=""
   ANOM1:=CTOD(DIACAMBIARFTO(__DATE__))
   ANOM2:=0
   PROGRAMA2:=PROGRAMA()
   DO CASE
   CASE PROGRAMA2="SUIZO"
      FNOM2:="SUIZO Contabilidad" //2004 HARBOUR - 2005 xHarbour
                                  //20-02-2006 INDICES CDX
      ANOM2:=1993
   CASE PROGRAMA2="CONTA"
      FNOM2:="SUIZO Comercial"    //2004 HARBOUR - 2005 xHarbour
                                  //20-02-2006 INDICES CDX
      ANOM2:=1997
   CASE PROGRAMA2="CAJA"
      FNOM2:="SUIZO Caja"         //CLIPPER
      ANOM2:=1998
   CASE PROGRAMA2="REMESA"
      FNOM2:="SUIZO Remesa"       //2004 HARBOUR - 2005 xHarbour
                                  //21-02-2006 INDICES CDX
      ANOM2:=1998
   CASE PROGRAMA2="COMISION"
      FNOM2:="SUIZO Comisiones"   //CLIPPER
      ANOM2:=2002
   CASE PROGRAMA2="AGENDA"
      FNOM2:="SUIZO Agenda"       //CLIPPER
      ANOM2:=1999
   CASE PROGRAMA2="CLUB"
      FNOM2:="SUIZO Club Ajedrez" //CLIPPER
      ANOM2:=1999
   CASE PROGRAMA2="LIGA"
      FNOM2:="SUIZO Liga"         //CLIPPER
      ANOM2:=1999
   CASE PROGRAMA2="TORNEO"
      FNOM2:="SUIZO Torneo"       //CLIPPER
      ANOM2:=1999
   CASE PROGRAMA2="DIM_PAS"
      FNOM2:="SUIZO Dim_pas"      //2004 HARBOUR - 2005 xHarbour
      ANOM2:=1999
   CASE PROGRAMA2="SUICONTA"
      FNOM2:="SUIZO Contabilidad"  //2007 HMG-EXT
      ANOM2:=2007 //12-03-07 Empiezo
   CASE PROGRAMA2="SUIALMA"
      FNOM2:="SUIZO Almacen"       //2008 HMG-EXT
      ANOM2:=2008 //28-06-08 Empiezo
   ENDCASE
   IF UPPER(LLAMADA)="VERSION"
      IF ANOM2>0
         IF UPPER(VERSION())="CLIPPER"
            FNOM2:=FNOM2+" c"
         ELSE
            FNOM2:=FNOM2+" v"
         ENDIF
         FNOM2:=FNOM2+LTRIM(STR(YEAR(ANOM1)-ANOM2))+"."+LTRIM(STR(MONTH(ANOM1)))
      ENDIF
   ENDIF
   RETURN(FNOM2)
*
FUNCTION EMPRUTANY(NUMEMP2,NUMANY2,NOMPROG)
   LOCAL NUMSEL:=SELECT()
   EMPESTOY:=RECNO()
   NOMPROG:=IF(NOMPROG=NIL,NOMPROG(),NOMPROG)
   DO CASE
   CASE PROGRAMA()="SUICONTA"
      IF .NOT. FILE(RUTAPROGRAMA+"\EMPRESA.DBF") .OR. ;
         .NOT. FILE(RUTAPROGRAMA+"\EMPRESA.CDX")
         RETURN("")
      ENDIF
      AbrirDBF("EMPRESA",,,,RUTAPROGRAMA,)
   CASE PROGRAMA()="SUIALMA"
      IF .NOT. FILE(RUTAPROGRAMA+"\EMPCON.DBF") .OR. ;
         .NOT. FILE(RUTAPROGRAMA+"\EMPCON.CDX")
         RETURN("")
      ENDIF
      AbrirDBF("EMPCON",,,,RUTAPROGRAMA,)
   ENDCASE
   IF VALTYPE(NUMEMP2)="N"
      SEEK NUMEMP2
      IF NUMANY2=0 //IR A LA EMPRESA NUMEMP2
         NUMANY2=EJERCICIO
      ENDIF
   ELSE
      NUMEMP2:=ALLTRIM(NUMEMP2)
      IF LEN(NUMEMP2)>10
         NUMEMP2:=LEFT(NUMEMP2,LEN(NUMEMP2)-6)  //QUITAR (A¥O)
      ENDIF
      LOCATE FOR EMP=NUMEMP2
   ENDIF
   DO WHILE .T.
      DO CASE
      CASE NUMANY2=EJERCICIO
         RUTANY2:=RUTAPROGRAMA+"\"+RTRIM(RUTA)
         EXIT
      CASE NUMANY2>EJERCICIO .AND. NEMPSIG<>0
         SEEK NEMPSIG
         LOOP
      CASE NUMANY2<EJERCICIO .AND. NEMPANT<>0
         SEEK NEMPANT
         LOOP
      OTHERWISE
         RUTANY2:=" "
         EXIT
      ENDCASE
   ENDDO
   USE
   SELEC &NUMSEL
   IF EMPESTOY<>0
      GO EMPESTOY
   ENDIF
   RETURN(RUTANY2)
