***FCIERRE= 1-APUNTES+CIERRE 2-APUNTES
***SALDO=SALDO INICIAL***
#include "minigui.ch"
#include "winprint.ch"

FUNCTION FIC_CIERRE(CODIGOA,CODIGOB,FEC1,FEC2,FCIERRE,DIVI2)
//FCIERRE=0 ->NO INCLUIR CIERRE
//FCIERRE=1 ->NO INCLUIR CIERRE
//FCIERRE=2 ->SI INCLUIR CIERRE (SIN ASIENTO DE CIERRE)
//FCIERRE=3 ->SI INCLUIR CIERRE (CON ASIENTO DE CIERRE)

   DEFINE WINDOW W_FicCie1 ;
      AT 10,10 ;
      WIDTH 400 HEIGHT 130 ;
      TITLE 'Actualizando ficheros' ;
      MODAL NOSIZE ;
      ON INIT FIC_CIERRE2(CODIGOA,CODIGOB,FEC1,FEC2,FCIERRE,DIVI2)

      @015,10 LABEL L_Cuentas VALUE 'Cuentas' AUTOSIZE TRANSPARENT
      @010,80 PROGRESSBAR P_Progres1 RANGE 0 , 100 WIDTH 300 HEIGHT 20 SMOOTH

      @045,10 LABEL L_Apuntes VALUE 'Apuntes' AUTOSIZE TRANSPARENT
      @040,80 PROGRESSBAR P_Progres2 RANGE 0 , 100 WIDTH 300 HEIGHT 20 SMOOTH

      @075,10 LABEL L_Cierre VALUE 'Cierre' AUTOSIZE TRANSPARENT
      @070,80 PROGRESSBAR P_Progres3 RANGE 0 , 100 WIDTH 300 HEIGHT 20 SMOOTH

   END WINDOW
   VentanaCentrar("W_FicCie1","Ventana1")
   ACTIVATE WINDOW W_FicCie1




STATIC FUNCTION FIC_CIERRE2(CODIGOA,CODIGOB,FEC1,FEC2,FCIERRE,DIVI2)
LOCAL YCOD,YNOM,YSAL,YSAL2:=0,YDEB,YHAB,CONTADOR,NUM:=1

   IF FILE(gettempdir()+"FINSUIC.DBF")
      AbrirDBF("FINSUIC","SIN_INDICE",,,gettempdir())
      FINSUIC->( DBCLOSEAREA() )
      FERASE(gettempdir()+"FINSUIC.DBF")
      FERASE(gettempdir()+"FINSUIC.CDX")
   ENDIF
   AbrirDBF("CUENTAS",,,,,1)
   aArq:=DBSTRUCT()
   DBCreate( gettempdir()+'FINSUIC' , aArq  )
   AbrirDBF("FINSUIC","SIN_INDICE",,"Exclusive",gettempdir())
   FICFINSUIC:=gettempdir()+"FINSUIC"
   INDEX ON CODCTA TO &FICFINSUIC

AbrirDBF("CUENTAS",,,,,1)
GO TOP
CONTADOR=0
DO WHILE .NOT. EOF()
   CONTADOR++
   W_FicCie1.P_Progres1.Value:=(CONTADOR*100)/LASTREC()
   IF INT(CODCTA/DIVI2)<CODIGOA .OR. INT(CODCTA/DIVI2)>CODIGOB
      SKIP
      LOOP
   ENDIF
   YCOD=INT(CODCTA/DIVI2)
   YNOM=NOMCTA
   AbrirDBF("FINSUIC",,,"Exclusive",gettempdir())
   SEEK YCOD
   IF EOF()
      APPEND BLANK
      REPLACE CODCTA WITH YCOD
      REPLACE NOMCTA WITH YNOM
   ENDIF
   AbrirDBF("CUENTAS",,,,,1)
   SKIP
ENDDO
FOR N=1 TO 2
   IF N=2 .AND. FCIERRE<2
      EXIT
   ENDIF
   IF N=1
      FICAPU2:="APUNTES"
   ELSE
      FICAPU2:="CIERRE"
   ENDIF
   AbrirDBF(FICAPU2)
   GO TOP
   CONTADOR=0
DO WHILE .NOT. EOF()
   CONTADOR++
   IF N=1
      W_FicCie1.P_Progres2.Value:=(CONTADOR*100)/LASTREC()
   ELSE
      W_FicCie1.P_Progres3.Value:=(CONTADOR*100)/LASTREC()
   ENDIF
   IF NASI=999998 .AND. FCIERRE<>3 //SIN ASIENTO DE CIERRE
      SKIP
      LOOP
   ENDIF
   IF INT(CODCTA/DIVI2)>=CODIGOA .AND. INT(CODCTA/DIVI2)<=CODIGOB
      DO CASE
         CASE FECHA<FEC1 .OR. NASI=1
            YSAL=DEBE-HABER
            YDEB=0
            YHAB=0
            YCOD=INT(CODCTA/DIVI2)
         CASE FECHA>=FEC1 .AND. FECHA<=FEC2
            YSAL=0
            YDEB=DEBE
            YHAB=HABER
            YCOD=INT(CODCTA/DIVI2)
         OTHERWISE
            YCOD=0
      ENDCASE
      IF YCOD<>0
         AbrirDBF("FINSUIC",,,"Exclusive",gettempdir())
         SEEK YCOD
         IF EOF()
            APPEND BLANK
            REPLACE CODCTA WITH YCOD
            REPLACE NOMCTA WITH "* CUENTA INEXISTENTE *                  "
         ENDIF
         REPLACE DEBE WITH DEBE+YDEB
         REPLACE HABER WITH HABER+YHAB
         REPLACE SALDO WITH SALDO+YSAL
         AbrirDBF(FICAPU2)
      ENDIF
   ENDIF
   SKIP
ENDDO
NEXT

W_FicCie1.release
