* PONER LOS PUNTOS DE MIL A LOS NUMEROS
*
FUNCTION MIL(MIL1,MIL2,MIL3)
MIL1:=ROUND(MIL1,MIL3)

IF MIL3>0
   *** QUITAR ALGUN DECIMAL ***
   MILENT:=LTRIM(STR(MIL1))
   MILENT:=AT(".",MILENT)-1
   MILENT:=INT((MILENT-1)/3)+MILENT+MIL3+1 //LA COMA
   IF MILENT>MIL2 .AND. MILENT-MIL3<=MIL2
      MIL3:=MIL2-(MILENT-MIL3)
      MIL1:=ROUND(MIL1,MIL3)
   ENDIF
   *** FIN QUITAR ALGUN DECIMAL ***
   IF MIL3>0
      MILDEC:=ALLTRIM(STR(MIL1))
      MILDEC:=","+SUBSTR(MILDEC,AT(".",MILDEC)+1,MIL3)
   ELSE
      MILDEC:=""
   ENDIF
ELSE
   MILDEC:=""
ENDIF

MIL4:=MIL_PUNTOS(INT(MIL1),MIL1)+MILDEC
MIL5:=STRTRAN(MIL4,".","") //QUITAR LOS PUNTOS

DO CASE
   CASE LEN(MIL4)<=MIL2   //CON PUNTOS
      MIL4:=PADL(MIL4,MIL2," ")
   CASE LEN(MIL4)>MIL2 .AND. LEN(MIL5)<=MIL2  //SIN PUNTOS
      MIL4:=PADL(MIL5,MIL2," ")
   CASE LEN(MIL5)>MIL2    //SE PASA
      IF MIL3>0           //CON PUNTOS SIN DECIMALES
         MIL4:=MIL_PUNTOS(ROUND(MIL1,0),ROUND(MIL1,0))
      ENDIF
      IF LEN(MIL4)>MIL2   //SIN PUNTOS SIN DECIMALES
         MIL5:=ALLTRIM(STR(ROUND(MIL1,0)))
         IF LEN(MIL5)<=MIL2
            MIL4:=MIL5
         ENDIF
      ENDIF
      IF LEN(MIL4)>MIL2   //QUITAR MILES
         MILM:=""
         MILM2:=""
         DO WHILE LEN(MIL4+MILM)>MIL2 .AND. LEN(MIL4)>4 .AND. MIL2>=4
            MIL1:=ROUND(MIL1/1000,0)
            MIL4:=MIL_PUNTOS(MIL1,MIL1)
            MILM2:=MILM2+"M"
            MILM:="M"
            IF LEN(MILM2)>1
               MILM:="M"+LTRIM(STR(LEN(MILM2)))
            ENDIF
            IF MIL2=4 .AND. LEN(MILM)>1 //SOLO SALE 1 M
               MILM:="****"
            ENDIF
         ENDDO
         MIL4:=MIL4+MILM
      ENDIF
      IF LEN(MIL4)>MIL2   //ERROR
         MIL4:=PADL("*",MIL2,"*")
      ELSE
         MIL4:=PADL(MIL4,MIL2," ")
      ENDIF
ENDCASE

RETURN(MIL4)

* PONER LOS PUNTOS DE MIL A LOS NUMEROS ENTEROS
*
FUNCTION MIL_PUNTOS(MILP,MIL1)

IF MILP>=0
   MILP2=ALLTRIM(STR(MILP))
ELSE
   MILP2=ALLTRIM(STR(MILP*-1))
ENDIF

IF LEN(MILP2)>3
   MILP2=LEFT(MILP2,LEN(MILP2)-3)+"."+RIGHT(MILP2,3)
ENDIF

DO WHILE AT(".",MILP2)>4
   MILP2=LEFT(MILP2,AT(".",MILP2)-4)+"."+SUBSTR(MILP2,AT(".",MILP2)-3,LEN(MILP2))
ENDDO

IF MIL1<0 //PONER MENOS A -0,5
   MILP2="-"+MILP2
ENDIF

RETURN(MILP2)


* PONER LOS PUNTOS DE MIL A LOS NUMEROS DE GET Y SAY
*
FUNCTION MIL2(MIL2,MIL3)
MIL4:=""
IF MIL3>0
   MIL4="."+PADL("9",MIL3,"9")
   MIL3++
ENDIF
MIL2=MIL2-MIL3
DO WHILE MIL2>4
   MIL4=",999"+MIL4
   MIL2=MIL2-4
ENDDO
MIL4="@E "+PADL("9",MIL2,"9")+MIL4
RETURN(MIL4)


* QUITAR LOS PUNTOS DE MIL Y CONVERTIRLO EN NUMERO
*
FUNCTION MILQUITAR(MIL1)
   MIL1:=STRTRAN(MIL1,".","") //QUITAR LOS PUNTOS
   MIL1:=STRTRAN(MIL1,",",".") //CAMBIAR LA COMA
   MIL1:=VAL(MIL1) //CONERTIRLO EN NUMERO
RETURN(MIL1)


* PASAR BYTES A MEDIDAS SUPERIORES
*
FUNCTION MilByte(MIL1)
MIL2:="By"
IF MIL1>=1024
   MIL1:=MIL1/1024
   MIL2:="KB"
ENDIF
IF MIL1>=1024
   MIL1:=MIL1/1024
   MIL2:="MB"
ENDIF
IF MIL1>=1024
   MIL1:=MIL1/1024
   MIL2:="GB"
ENDIF
MIL3:=MIL(MIL1,4,2)+" "+MIL2
RETURN(MIL3)
