FUNCTION MDA_NOM1(MONEANY)
   IF MONEANY>=2002
      MONENOM:="EURO"
   ELSE
      MONENOM:="PTAS"
   ENDIF
   RETURN(MONENOM)
*
FUNCTION MDA_NOM2(MONEANY)
   IF MONEANY>=2002
      MONENOM:="EUROS  "
   ELSE
      MONENOM:="PESETAS"
   ENDIF
   RETURN(MONENOM)
*
FUNCTION MDA_DEC(MONEANY,MONEDEC)
   MONEDEC:=IF(MONEDEC=NIL, 0 ,MONEDEC)
   IF MONEANY>=2002
      MONEDA_NUM2:=2+MONEDEC
   ELSE
      MONEDA_NUM2:=0+MONEDEC
   ENDIF
   RETURN(MONEDA_NUM2)
*
FUNCTION MDA_SIDEC(MONEANY)
   IF MDA_DEC(MONEANY)<>0
      MONEDA_NUM2:=1
   ELSE
      MONEDA_NUM2:=0
   ENDIF
   RETURN(MONEDA_NUM2)
*
FUNCTION PTA_EURO(MONE2,MONEANY,MONEDEC)
   MONEANY:=IF(MONEANY=NIL,EJERANY,MONEANY)
   MONEDEC:=IF(MONEDEC=NIL, 0 ,MONEDEC)
   MONE2:=MONE2/166.386
   MONE2:=ROUND(MONE2,MDA_DEC(MONEANY,MONEDEC))
   RETURN(MONE2)
*
FUNCTION EURO_PTA(MONE2)
   MONE2:=MONE2*166.386
   MONE2:=ROUND(MONE2,0)
   RETURN(MONE2)
*
FUNCTION MDA_PTA(MONE2,MONEANY,MONEDEC)
   MONEDEC:=IF(MONEDEC=NIL, 0 ,MONEDEC)
   IF MONEANY>=2002
      MONE2:=MONE2*166.386
      MONE2:=ROUND(MONE2,MONEDEC)
   ENDIF
   RETURN(MONE2)
*
FUNCTION MDA_EURO(MONE2,MONEANY,MONEDEC)
   MONEDEC:=IF(MONEDEC=NIL, 0 ,MONEDEC)
   IF MONEANY<2002
      MONE2:=MONE2/166.386
      MONE2:=ROUND(MONE2,MDA_DEC(EJERANY,MONEDEC))
   ENDIF
   RETURN(MONE2)
*
FUNCTION MDA_PASAR(MONE2,MONEANY,MONEDEC)
   MONEDEC:=IF(MONEDEC=NIL, 0 ,MONEDEC)
   IF EJERANY>=2002
      MONE2:=MDA_EURO(MONE2,MONEANY,MONEDEC)
   ELSE
      MONE2:=MDA_PTA(MONE2,MONEANY,MONEDEC)
   ENDIF
   RETURN(MONE2)
*
