Function CodPostal(CPVENTANA,CPCONTROL1,CPCONTROL2,CPCONTROL3)
   CPCONTROL1:=IF(CPCONTROL1=NIL,"T_Codpos"   ,CPCONTROL1)
   CPCONTROL2:=IF(CPCONTROL2=NIL,"T_Poblacion",CPCONTROL2)
   CPCONTROL3:=IF(CPCONTROL3=NIL,"T_Provincia",CPCONTROL3)
   NUMSEL2:=SELEC()
   CODPOS2:=GetProperty(CPVENTANA,CPCONTROL1,"Value")
   IF LEN(LTRIM(CODPOS2))=5
      SetProperty(CPVENTANA,CPCONTROL2,"Value",CP_POB(CODPOS2))
      SetProperty(CPVENTANA,CPCONTROL3,"Value",CP_PROV(CODPOS2))
   ENDIF
   SELEC(NUMSEL2)

FUNCTION CP_PROV(NUMPCIA1) //NUMPCIA1=CODIGO POSTAL '46970'
	IF VALTYPE(NUMPCIA1)="C"
	   NUMPCIA2:=VAL(NUMPCIA1)
	ELSE
	   NUMPCIA2:=NUMPCIA1
	ENDIF
	IF NUMPCIA2>999
		NUMPCIA2:=VAL(LEFT(STR(NUMPCIA2,5),2))
	ENDIF

   NOMPCIA2:=""
   DO CASE
   CASE FILE(RUTAPROGRAMA+"\CODPOS.DBF")
      CP_RUTA:=RUTAPROGRAMA
   CASE FILE(LEFT(RUTAPROGRAMA,RAT("\",RUTAPROGRAMA)-1)+"\SUIALMA\CODPOS.DBF")
      CP_RUTA:=LEFT(RUTAPROGRAMA,RAT("\",RUTAPROGRAMA)-1)+"\SUIALMA"
   OTHERWISE
      CP_RUTA:="quenoloencuentre"
   ENDCASE
   IF FILE(CP_RUTA+"\CODPOS.DBF")
	   NUMSEL:=SELECT()
      AbrirDBF("CodPos",,,,CP_RUTA)
	   EstoyCodPos2:=RECNO()
      SEEK STRZERO(NUMPCIA2,2)+SPACE(3)
      IF .NOT. EOF()
         NOMPCIA2:=NOMPOS
      ENDIF
		GO EstoyCodPos2
	   SELEC(NUMSEL)
   ENDIF

IF LEN(NOMPCIA2)=0
   DO CASE
   CASE NUMPCIA2=1
      NOMPCIA2:="Alava"
   CASE NUMPCIA2=2
      NOMPCIA2:="Albacete"
   CASE NUMPCIA2=3
      NOMPCIA2:="Alicante"
   CASE NUMPCIA2=4
      NOMPCIA2:="Almeria"
   CASE NUMPCIA2=5
      NOMPCIA2:="Avila"
   CASE NUMPCIA2=6
      NOMPCIA2:="Badajoz"
   CASE NUMPCIA2=7
      NOMPCIA2:="Baleares"
   CASE NUMPCIA2=8
      NOMPCIA2:="Barcelona"
   CASE NUMPCIA2=9
      NOMPCIA2:="Burgos"
   CASE NUMPCIA2=10
      NOMPCIA2:="Caceres"
   CASE NUMPCIA2=11
      NOMPCIA2:="Cadiz"
   CASE NUMPCIA2=12
      NOMPCIA2:="Castellón"
   CASE NUMPCIA2=13
      NOMPCIA2:="Ciudad Real"
   CASE NUMPCIA2=14
      NOMPCIA2:="Cordoba"
   CASE NUMPCIA2=15
      NOMPCIA2:="La Coruña"
   CASE NUMPCIA2=16
      NOMPCIA2:="Cuenca"
   CASE NUMPCIA2=17
      NOMPCIA2:="Gerona"
   CASE NUMPCIA2=18
      NOMPCIA2:="Granada"
   CASE NUMPCIA2=19
      NOMPCIA2:="Guadalajara"
   CASE NUMPCIA2=20
      NOMPCIA2:="Guipuzcoa"
   CASE NUMPCIA2=21
      NOMPCIA2:="Huelva"
   CASE NUMPCIA2=22
      NOMPCIA2:="Huesca"
   CASE NUMPCIA2=23
      NOMPCIA2:="Jaén"
   CASE NUMPCIA2=24
      NOMPCIA2:="León"
   CASE NUMPCIA2=25
      NOMPCIA2:="Lerida"
   CASE NUMPCIA2=26
      NOMPCIA2:="La Rioja"
   CASE NUMPCIA2=27
      NOMPCIA2:="Lugo"
   CASE NUMPCIA2=28
      NOMPCIA2:="Madrid"
   CASE NUMPCIA2=29
      NOMPCIA2:="Malaga"
   CASE NUMPCIA2=30
      NOMPCIA2:="Murcia"
   CASE NUMPCIA2=31
      NOMPCIA2:="Navarra"
   CASE NUMPCIA2=32
      NOMPCIA2:="Orense"
   CASE NUMPCIA2=33
      NOMPCIA2:="Asturias"
   CASE NUMPCIA2=34
      NOMPCIA2:="Palencia"
   CASE NUMPCIA2=35
      NOMPCIA2:="Las Palmas"
   CASE NUMPCIA2=36
      NOMPCIA2:="Pontevedra"
   CASE NUMPCIA2=37
      NOMPCIA2:="Salamanca"
   CASE NUMPCIA2=38
      NOMPCIA2:="Sta.Cruz de Tenerife"
   CASE NUMPCIA2=39
      NOMPCIA2:="Cantabria"
   CASE NUMPCIA2=40
      NOMPCIA2:="Segovia"
   CASE NUMPCIA2=41
      NOMPCIA2:="Sevilla"
   CASE NUMPCIA2=42
      NOMPCIA2:="Soria"
   CASE NUMPCIA2=43
      NOMPCIA2:="Tarragona"
   CASE NUMPCIA2=44
      NOMPCIA2:="Teruel"
   CASE NUMPCIA2=45
      NOMPCIA2:="Toledo"
   CASE NUMPCIA2=46
      NOMPCIA2:="Valencia"
   CASE NUMPCIA2=47
      NOMPCIA2:="Valladolid"
   CASE NUMPCIA2=48
      NOMPCIA2:="Vizcaya"
   CASE NUMPCIA2=49
      NOMPCIA2:="Zamora"
   CASE NUMPCIA2=50
      NOMPCIA2:="Zaragoza"
   CASE NUMPCIA2=51
      NOMPCIA2:="Ceuta"
   CASE NUMPCIA2=52
      NOMPCIA2:="Melilla"
   OTHERWISE
      NOMPCIA2:="     "
   ENDCASE
ENDIF
RETURN(NOMPCIA2)

FUNCTION CP_POB(NUMPCIA1) //NUMPCIA1=CODIGO POSTAL '46970'
   NUMPCIA2:=LTRIM(NUMPCIA1)
   NOMPCIA2:=""
   DO CASE
   CASE FILE(RUTAPROGRAMA+"\CODPOS.DBF")
      CP_RUTA:=RUTAPROGRAMA
   CASE FILE(LEFT(RUTAPROGRAMA,RAT("\",RUTAPROGRAMA)-1)+"\SUIALMA\CODPOS.DBF")
      CP_RUTA:=LEFT(RUTAPROGRAMA,RAT("\",RUTAPROGRAMA)-1)+"\SUIALMA"
   OTHERWISE
      RETURN
   ENDCASE
   IF FILE(CP_RUTA+"\CODPOS.DBF")
      AbrirDBF("CodPos",,,,CP_RUTA)
      SEEK NUMPCIA2
      IF .NOT. EOF()
         NOMPCIA2:=NOMPOS
      ENDIF
   ENDIF
IF LEN(NOMPCIA2)=0
   DO CASE
   CASE NUMPCIA2="46035"
      NOMPCIA2:="Benimamet"
   CASE NUMPCIA2="46100"
      NOMPCIA2:="Burjassot"
   CASE NUMPCIA2="46900"
      NOMPCIA2:="Torrent"
   CASE NUMPCIA2="46920"
      NOMPCIA2:="Mislata"
   CASE NUMPCIA2="46930"
      NOMPCIA2:="Quart de Poblet"
   CASE NUMPCIA2="46940"
      NOMPCIA2:="Manises"
   CASE NUMPCIA2="46950"
      NOMPCIA2:="Xirivella"
   CASE NUMPCIA2="46960"
      NOMPCIA2:="Aldaia"
   CASE NUMPCIA2="46970"
      NOMPCIA2:="Alaquas"
   CASE NUMPCIA2="46980"
      NOMPCIA2:="Paterna"
   CASE NUMPCIA2="46989"
      NOMPCIA2:="Terramelar -Paterna"
   OTHERWISE
      NOMPCIA2:=""
   ENDCASE
ENDIF
RETURN(NOMPCIA2)

FUNCTION CP_GRABAR(CODPOS1,CODPOB1,CODPRO1)
   DO CASE
   CASE FILE(RUTAPROGRAMA+"\CODPOS.DBF")
      CP_RUTA:=RUTAPROGRAMA
   CASE FILE(LEFT(RUTAPROGRAMA,RAT("\",RUTAPROGRAMA)-1)+"\SUIALMA\CODPOS.DBF")
      CP_RUTA:=LEFT(RUTAPROGRAMA,RAT("\",RUTAPROGRAMA)-1)+"\SUIALMA"
   OTHERWISE
      RETURN
   ENDCASE
   AbrirDBF("CodPos",,,,CP_RUTA)
   SEEK CODPOS1
   IF EOF()
      APPEND BLANK
      IF RLOCK()
         REPLACE CODPOS WITH CODPOS1
         REPLACE NOMPOS WITH CODPOB1
      ENDIF
   ENDIF
   SEEK LEFT(CODPOS1,2)+SPACE(3)
   IF EOF()
      APPEND BLANK
      IF RLOCK()
         REPLACE CODPOS WITH LEFT(CODPOS1,2)
         REPLACE NOMPOS WITH CODPRO1
      ENDIF
   ENDIF
