FUNCTION BUSRUTAEMP(BUSRUTAEMP1,BUSNUMEMP1,BUSNUMANY1,BUSNOMPROG1)
   BUSNUMEMP1:=IF(VALTYPE(BUSNUMEMP1)="N",STR(BUSNUMEMP1),BUSNUMEMP1)
   BUSNUMEMP2:=" "
   BUSRUTAEMP2:=" "
   NUMSELBUS:=SELEC()
   DO CASE
   CASE BUSNOMPROG1="ESCOLA"
      BUSRUTAEMP2:=LTRIM(BUSRUTAEMP1)
      IF FILE(BUSRUTAEMP2+"\EMPRESA.DBF") .AND. ;
         FILE(BUSRUTAEMP2+"\EMPRESA.CDX")
         AbrirDBF("EMPRESA",,,,BUSRUTAEMP2)
         SEEK VAL(BUSNUMEMP1)
         DO WHILE .T.
            DO CASE
            CASE BUSNUMANY1=0
               SEEK VAL(BUSNUMEMP1)
               BUSRUTAEMP2:=BUSRUTAEMP2+"\"+RTRIM(RUTA)
               BUSNUMEMP2:=STR(CODEMP)
               EXIT
            CASE BUSNUMANY1>=1 .AND. BUSNUMANY1<=999
               SEEK BUSNUMANY1
               BUSRUTAEMP2:=BUSRUTAEMP2+"\"+RTRIM(RUTA)
               BUSNUMEMP2:=STR(NEMP)
               EXIT
            CASE BUSNUMANY1=EJERCICIO
               BUSRUTAEMP2:=BUSRUTAEMP2+"\"+RTRIM(RUTA)
               BUSNUMEMP2:=STR(CODEMP)
               EXIT
            CASE BUSNUMANY1>EJERCICIO .AND. NEMPSIG<>0
               SEEK NEMPSIG
               LOOP
            CASE BUSNUMANY1<EJERCICIO .AND. NEMPANT<>0
               SEEK NEMPANT
               LOOP
            OTHERWISE
               BUSRUTAEMP2:=" "
               BUSNUMEMP2:=" "
               EXIT
            ENDCASE
         ENDDO
         EMPRESA->( DBCLOSEAREA() )
      ENDIF
   CASE BUSNOMPROG1="SUICONTA"
      BUSRUTAEMP2:=LEFT(BUSRUTAEMP1,RAT("SUIZO",UPPER(BUSRUTAEMP1))-2)
      IF AT("SUIZO",UPPER(BUSRUTAEMP2))=0
         BUSRUTAEMP2:=BUSRUTAEMP1
      ENDIF
      IF AT("SUICONTA",UPPER(BUSRUTAEMP1))=0 .AND. AT("SUIALMA",UPPER(BUSRUTAEMP1))<>0
         BUSRUTAEMP2:=STRTRAN(UPPER(BUSRUTAEMP1),"SUIALMA","SUICONTA")
      ENDIF
      IF FILE(BUSRUTAEMP2+"\EMPRESA.DBF") .AND. ;
         FILE(BUSRUTAEMP2+"\EMPRESA.CDX")
         AbrirDBF("EMPRESA",,,,BUSRUTAEMP2)
         SEEK VAL(BUSNUMEMP1)
         DO WHILE .T.
            DO CASE
            CASE BUSNUMANY1=0
               SEEK VAL(BUSNUMEMP1)
               BUSRUTAEMP2:=BUSRUTAEMP2+"\"+RTRIM(RUTA)
               BUSNUMEMP2:=STR(NEMP)
               EXIT
            CASE BUSNUMANY1>=1 .AND. BUSNUMANY1<=999
               SEEK BUSNUMANY1
               BUSRUTAEMP2:=BUSRUTAEMP2+"\"+RTRIM(RUTA)
               BUSNUMEMP2:=STR(NEMP)
               EXIT
            CASE BUSNUMANY1=EJERCICIO
               BUSRUTAEMP2:=BUSRUTAEMP2+"\"+RTRIM(RUTA)
               BUSNUMEMP2:=STR(NEMP)
               EXIT
            CASE BUSNUMANY1>EJERCICIO .AND. NEMPSIG<>0
               SEEK NEMPSIG
               LOOP
            CASE BUSNUMANY1<EJERCICIO .AND. NEMPANT<>0
               SEEK NEMPANT
               LOOP
            OTHERWISE
               BUSRUTAEMP2:=" "
               BUSNUMEMP2:=" "
               EXIT
            ENDCASE
         ENDDO
         EMPRESA->( DBCLOSEAREA() )
      ENDIF
   CASE BUSNOMPROG1=="SUIALMA"
      BUSRUTAEMP2:=BUSRUTAEMP1
      IF AT("CONTA",UPPER(BUSRUTAEMP1))<>0 .AND. AT("SUICONTA",UPPER(BUSRUTAEMP1))=0
         BUSRUTAEMP2:=LEFT(BUSRUTAEMP1,RAT("CONTA",UPPER(BUSRUTAEMP1))-2)
      ENDIF
      IF AT("SUIALMA",UPPER(BUSRUTAEMP1))=0 .AND. AT("SUICONTA",UPPER(BUSRUTAEMP1))<>0
         BUSRUTAEMP2:=STRTRAN(UPPER(BUSRUTAEMP1),"SUICONTA","SUIALMA")
      ENDIF
      IF FILE(BUSRUTAEMP2+"\EMPCON.DBF") .AND. ;
         FILE(BUSRUTAEMP2+"\EMPCON.CDX")
         AbrirDBF("EMPCON",,,,BUSRUTAEMP2)
         SEEK VAL(BUSNUMEMP1)
         DO WHILE .T.
            DO CASE
            CASE BUSNUMANY1=0
               SEEK VAL(BUSNUMEMP1)
               BUSRUTAEMP2:=BUSRUTAEMP2+"\"+RTRIM(RUTA)
               BUSNUMEMP2:=STR(NEMP)
               EXIT
            CASE BUSNUMANY1>=1 .AND. BUSNUMANY1<=999
               SEEK BUSNUMANY1
               BUSRUTAEMP2:=BUSRUTAEMP2+"\"+RTRIM(RUTA)
               BUSNUMEMP2:=STR(NEMP)
               EXIT
            CASE BUSNUMANY1=EJERCICIO
               BUSRUTAEMP2:=BUSRUTAEMP2+"\"+RTRIM(RUTA)
               BUSNUMEMP2:=STR(NEMP)
               EXIT
            CASE BUSNUMANY1>EJERCICIO .AND. NEMPSIG<>0
               SEEK NEMPSIG
               LOOP
            CASE BUSNUMANY1<EJERCICIO .AND. NEMPANT<>0
               SEEK NEMPANT
               LOOP
            OTHERWISE
               BUSRUTAEMP2:=" "
               BUSNUMEMP2:=" "
               EXIT
            ENDCASE
         ENDDO
         EMPCON->( DBCLOSEAREA() )
      ENDIF
   CASE BUSNOMPROG1="CONTAELI"
      IF AT("EMP",UPPER(BUSRUTAEMP1))<>0
         BUSRUTAEMP2:=LEFT(BUSRUTAEMP1,RAT("EMP",UPPER(BUSRUTAEMP1))-2)
      ELSE
         BUSRUTAEMP2:=BUSRUTAEMP1
      ENDIF
      IF FILE(BUSRUTAEMP2+"\EMP\EMPRESA.DBF") .AND. ;
         FILE(BUSRUTAEMP2+"\EMP\EMPRESA.CDX")
         AbrirDBF("EMPRESA",,,,BUSRUTAEMP2+"\EMP")
         BUSNUMEMP1:=PADR(BUSNUMEMP1,LEN(COD)," ")
         SEEK BUSNUMEMP1
         IF EOF() .AND. VAL(BUSNUMEMP1)<>0
            LOCATE FOR VAL(COD)=VAL(BUSNUMEMP1)
            BUSNUMEMP1:=COD
         ENDIF
         DO WHILE .T.
            DO CASE
            CASE BUSNUMANY1=0
               SEEK BUSNUMEMP1
               BUSRUTAEMP2:=BUSRUTAEMP2+"\EMP"+RTRIM(COD)
               BUSNUMEMP2:=COD
               EXIT
            CASE BUSNUMANY1>=1 .AND. BUSNUMANY1<=999
               LOCATE FOR VAL(COD)=VAL(BUSNUMEMP1)
               BUSRUTAEMP2:=BUSRUTAEMP2+"\"+RTRIM(RUTA)
               BUSNUMEMP2:=STR(NEMP)
               EXIT
            CASE BUSNUMANY1>=1 .AND. BUSNUMANY1<=999
               SEEK BUSNUMANY1
               BUSRUTAEMP2:=BUSRUTAEMP2+"\"+RTRIM(RUTA)
               BUSNUMEMP2:=STR(NEMP)
               EXIT
            CASE BUSNUMANY1=VAL(EJERCICIO)
               BUSRUTAEMP2:=BUSRUTAEMP2+"\EMP"+RTRIM(COD)
               BUSNUMEMP2:=COD
               EXIT
            CASE BUSNUMANY1<VAL(EJERCICIO) .AND. VAL(HISTORICO)<>0
               SEEK HISTORICO
               LOOP
            CASE BUSNUMANY1>VAL(EJERCICIO)
               HISTORICO2:=HISTORICO
               LOCATE FOR COD=HISTORICO2
               IF EOF()
                  EXIT
               ENDIF
               LOOP
            OTHERWISE
               BUSRUTAEMP2:=" "
               BUSNUMEMP2:=" "
               EXIT
            ENDCASE
         ENDDO
         EMPRESA->( DBCLOSEAREA() )
      ENDIF
   CASE BUSNOMPROG1="FACTUE"
      IF AT("DBF",UPPER(BUSRUTAEMP1))<>0
         BUSRUTAEMP2:=LEFT(BUSRUTAEMP1,RAT("DBF",UPPER(BUSRUTAEMP1))-2)
      ELSE
         BUSRUTAEMP2:=BUSRUTAEMP1
      ENDIF
      IF FILE(BUSRUTAEMP2+"\DBF\EMPRESA.DBF") .AND. ;
         FILE(BUSRUTAEMP2+"\DBF\EMPRESA.CDX")
         AbrirDBF("EMPRESA",,,,BUSRUTAEMP2+"\DBF")
         BUSNUMEMP1:=PADR(BUSNUMEMP1,LEN(CODEMP)," ")
         SEEK BUSNUMEMP1
         IF EOF() .AND. VAL(BUSNUMEMP1)<>0
            LOCATE FOR VAL(CODEMP)=VAL(BUSNUMEMP1)
            BUSNUMEMP1:=CODEMP
         ENDIF
         NOMEMP2:=LEFT(CNOMBRE,5)
         GO BOTT
         DO WHILE .NOT. BOF()
            DO CASE
            CASE BUSNUMANY1=0
               SEEK BUSNUMEMP1
               BUSRUTAEMP2:=BUSRUTAEMP2+"\DBF"+RTRIM(CODEMP)
               BUSNUMEMP2:=CODEMP
               EXIT
            CASE BUSNUMANY1>=1 .AND. BUSNUMANY1<=999
               LOCATE FOR VAL(COD)=VAL(BUSNUMEMP1)
               BUSRUTAEMP2:=BUSRUTAEMP2+"\"+RTRIM(RUTA)
               BUSNUMEMP2:=STR(NEMP)
               EXIT
            CASE AT(STR(BUSNUMANY1,4),CNOMBRE)<>0 .AND. AT(NOMEMP2,CNOMBRE)<>0
               BUSRUTAEMP2:=BUSRUTAEMP2+"\DBF"+RTRIM(CODEMP)
               BUSNUMEMP2:=CODEMP
               EXIT
            ENDCASE
            SKIP -1
         ENDDO
         EMPRESA->( DBCLOSEAREA() )
      ENDIF
   ENDCASE
   SELEC(NUMSELBUS)
   RETURN({BUSRUTAEMP2,BUSNUMEMP2})

FUNCTION aRUTAEMP(BUSRUTAEMP1,BUSNOMPROG1,BUSNOMAPLI1)
   BUSNOMPROG1:=IF(BUSNOMPROG1=NIL,"",BUSNOMPROG1)
   aRUTAEMP:={}
   NUMSELBUS:=SELEC()
   DO CASE
   CASE BUSNOMPROG1="ESCOLA"
      DO CASE
      CASE AT("ESCOLA",UPPER(BUSRUTAEMP1))<>0
         BUSRUTAEMP2:=LEFT(BUSRUTAEMP1,RAT("ESCOLA",UPPER(BUSRUTAEMP1))+5)
      CASE AT("PRUEBAS",UPPER(BUSRUTAEMP1))<>0
         BUSRUTAEMP2:=LEFT(BUSRUTAEMP1,RAT("PRUEBAS",UPPER(BUSRUTAEMP1))+6)
      OTHERWISE
         BUSRUTAEMP2:=BUSRUTAEMP1
      ENDCASE
      IF FILE(BUSRUTAEMP2+"\EMPRESA.DBF") .AND. ;
         FILE(BUSRUTAEMP2+"\EMPRESA.CDX")
         AbrirDBF("EMPRESA",,,,BUSRUTAEMP2)
         GO TOP
         DO WHILE .NOT. EOF()
            AADD(aRUTAEMP, { RTRIM(STR(CODEMP))+"-"+RTRIM(NOMEMP)+" "+STR(EJERCICIO,4) , RTRIM(RUTA) , EJERCICIO , STR(CODEMP) } )
            SKIP
         ENDDO
         EMPRESA->( DBCLOSEAREA() )
      ENDIF
   CASE BUSNOMPROG1="SUICONTA" .OR. AT("SUICONTA",UPPER(BUSRUTAEMP1))<>0
      IF RAT("SUIZO",UPPER(BUSRUTAEMP1))=LEN(BUSRUTAEMP1)-7
         BUSRUTAEMP2:=LEFT(BUSRUTAEMP1, RAT("SUIZO",UPPER(BUSRUTAEMP1))-2 )
      ELSE
         BUSRUTAEMP2:=BUSRUTAEMP1
      ENDIF
      IF FILE(BUSRUTAEMP2+"\EMPRESA.DBF") .AND. ;
         FILE(BUSRUTAEMP2+"\EMPRESA.CDX")
         AbrirDBF("EMPRESA",,,,BUSRUTAEMP2)
         GO TOP
         DO WHILE .NOT. EOF()
            AADD(aRUTAEMP, { LTRIM(STR(NEMP))+"-"+RTRIM(EMP)+" "+STR(EJERCICIO,4) , RTRIM(RUTA) , EJERCICIO , STR(NEMP) } )
            SKIP
         ENDDO
         EMPRESA->( DBCLOSEAREA() )
      ENDIF
   CASE BUSNOMPROG1="SUIALMA" .OR. AT("SUIALMA",UPPER(BUSRUTAEMP1))<>0
      BUSRUTAEMP2:=BUSRUTAEMP1
      IF RAT("ALMA",UPPER(BUSRUTAEMP1))=LEN(BUSRUTAEMP1)-6
         BUSRUTAEMP2:=LEFT(BUSRUTAEMP1, RAT("ALMA",UPPER(BUSRUTAEMP1))-2 )
      ELSE
         BUSRUTAEMP2:=BUSRUTAEMP1
      ENDIF
      IF FILE(BUSRUTAEMP2+"\EMPCON.DBF") .AND. ;
         FILE(BUSRUTAEMP2+"\EMPCON.CDX")
         AbrirDBF("EMPCON",,,,BUSRUTAEMP2)
         GO TOP
         DO WHILE .NOT. EOF()
            AADD(aRUTAEMP, { LTRIM(STR(NEMP))+"-"+RTRIM(EMP)+" "+STR(EJERCICIO,4) , RTRIM(RUTA) , EJERCICIO , STR(NEMP) } )
            SKIP
         ENDDO
         EMPCON->( DBCLOSEAREA() )
      ENDIF
   CASE BUSNOMPROG1="CONTAELI" .OR. AT("GRUPOSP\CO",UPPER(BUSRUTAEMP1))<>0
      IF AT("EMP",UPPER(BUSRUTAEMP1))<>0
         BUSRUTAEMP2:=LEFT(BUSRUTAEMP1,RAT("EMP",UPPER(BUSRUTAEMP1))-2)
      ELSE
         BUSRUTAEMP2:=BUSRUTAEMP1
      ENDIF
      BUSRUTAEMP2:=BUSRUTAEMP2+"\EMP"
      IF FILE(BUSRUTAEMP2+"\EMPRESA.DBF") .AND. ;
         FILE(BUSRUTAEMP2+"\EMPRESA.CDX")
         AbrirDBF("EMPRESA",,,,BUSRUTAEMP2)
         GO TOP
         DO WHILE .NOT. EOF()
            AADD(aRUTAEMP, { RTRIM(COD)+"-"+RTRIM(NOMBRE)+" "+LEFT(EJERCICIO,4) , 'EMP'+RTRIM(COD) , VAL(EJERCICIO) , COD } )
            SKIP
         ENDDO
         EMPRESA->( DBCLOSEAREA() )
      ENDIF
   CASE BUSNOMPROG1="FACTUE" .OR. AT("GRUPOSP\FA",UPPER(BUSRUTAEMP1))<>0
      IF AT("DBF",UPPER(BUSRUTAEMP1))<>0
         BUSRUTAEMP2:=LEFT(BUSRUTAEMP1,RAT("DBF",UPPER(BUSRUTAEMP1))-2)
      ELSE
         BUSRUTAEMP2:=BUSRUTAEMP1
      ENDIF
      BUSRUTAEMP2:=BUSRUTAEMP2+"\DBF"
      IF FILE(BUSRUTAEMP2+"\EMPRESA.DBF") .AND. ;
         FILE(BUSRUTAEMP2+"\EMPRESA.CDX")
         AbrirDBF("EMPRESA",,,,BUSRUTAEMP2)
         GO TOP
         DO WHILE .NOT. EOF()
            IF RIGHT(RTRIM(CNOMBRE),1)=")"
               ANY2:=RIGHT(RTRIM(CNOMBRE),5)
               ANY2:=VAL(LEFT(ANY2,4))
            ELSE
               ANY2:=VAL(RIGHT(RTRIM(CNOMBRE),4))
            ENDIF
            AADD(aRUTAEMP, { RTRIM(CODEMP)+"-"+RTRIM(CNOMBRE) , 'DBF'+RTRIM(CODEMP) , ANY2 , CODEMP } )
            SKIP
         ENDDO
         EMPRESA->( DBCLOSEAREA() )
      ENDIF
   ENDCASE
   SELEC(NUMSELBUS)
   RETURN(aRUTAEMP)
