FUNCTION GrupoSP_saldocuenta(SP_CTA2,SP_DEBE2,SP_HABER2,SP_FECHA2)
   IF VAL(SP_CTA2)=0
      RETURN
   ENDIF

   NUMSEL2:=SELEC()
   ESTOY2:=RECNO()
   SELEC SUBCTA
   ORDCUE2:=INDEXORD()
   DBSETORDER(1)

   SEEK SP_CTA2
   IF EOF()
      APPEND BLANK
      IF RLOCK()
         REPLACE COD    WITH SP_CTA2
         REPLACE TITULO WITH "Alta "+Nombre_Programa()
         DBCOMMIT()
         DBUNLOCK()
      ENDIF
   ENDIF

   IF SP_DEBE2<>0
      IF RLOCK()
         REPLACE SUMADB WITH SUMADB+MDA_PTA(SP_DEBE2,YEAR(SP_FECHA2))
         NOM2:="SDB"+STRZERO(MONTH(SP_FECHA2),2)
         REPLACE &NOM2 WITH &NOM2+MDA_PTA(SP_DEBE2,YEAR(SP_FECHA2))
         REPLACE NDB WITH NDB+MDA_PTA(SP_DEBE2,YEAR(SP_FECHA2))
         NOM2:="NDB"+STRZERO(MONTH(SP_FECHA2),2)
         REPLACE &NOM2 WITH &NOM2+MDA_PTA(SP_DEBE2,YEAR(SP_FECHA2))
      
         REPLACE SUMADBEU WITH SUMADBEU+MDA_EURO(SP_DEBE2,YEAR(SP_FECHA2))
         NOM2:="SDB"+STRZERO(MONTH(SP_FECHA2),2)+"EU"
         REPLACE &NOM2 WITH &NOM2+MDA_EURO(SP_DEBE2,YEAR(SP_FECHA2))
         REPLACE NDBEU WITH NDBEU+MDA_EURO(SP_DEBE2,YEAR(SP_FECHA2))
         NOM2:="NDB"+STRZERO(MONTH(SP_FECHA2),2)+"EU"
         REPLACE &NOM2 WITH &NOM2+MDA_EURO(SP_DEBE2,YEAR(SP_FECHA2))
         DBCOMMIT()
         DBUNLOCK()
      ENDIF
   ENDIF

   IF SP_HABER2<>0
      IF RLOCK()
         REPLACE SUMAHB WITH SUMAHB+MDA_PTA(SP_HABER2,YEAR(SP_FECHA2))
         NOM2:="SHB"+STRZERO(MONTH(SP_FECHA2),2)
         REPLACE &NOM2 WITH &NOM2+MDA_PTA(SP_HABER2,YEAR(SP_FECHA2))
         REPLACE NHB WITH NHB+MDA_PTA(SP_HABER2,YEAR(SP_FECHA2))
         NOM2:="NHB"+STRZERO(MONTH(SP_FECHA2),2)
         REPLACE &NOM2 WITH &NOM2+MDA_PTA(SP_HABER2,YEAR(SP_FECHA2))
      
         REPLACE SUMAHBEU WITH SUMAHBEU+MDA_EURO(SP_HABER2,YEAR(SP_FECHA2))
         NOM2:="SHB"+STRZERO(MONTH(SP_FECHA2),2)+"EU"
         REPLACE &NOM2 WITH &NOM2+MDA_EURO(SP_HABER2,YEAR(SP_FECHA2))
         REPLACE NHBEU WITH NHBEU+MDA_EURO(SP_HABER2,YEAR(SP_FECHA2))
         NOM2:="NHB"+STRZERO(MONTH(SP_FECHA2),2)+"EU"
         REPLACE &NOM2 WITH &NOM2+MDA_EURO(SP_HABER2,YEAR(SP_FECHA2))
         DBCOMMIT()
         DBUNLOCK()
      ENDIF
   ENDIF

   DBSETORDER(ORDCUE2)
   SELEC(NUMSEL2)
   GO ESTOY2

RETURN
