FUNCTION icobus(NOMICO)
RUTAICO:=""
aICO2:={".ico",".bmp",".jpg",".gif"}
FOR nICO2=1 TO LEN(aICO2)
	NOMICO2:=NOMICO+aICO2[nICO2]
	DO CASE
	CASE FILE(LEFT(RUTAPROGRAMA,RAT("\",RUTAPROGRAMA))+"Ico\"+NOMICO2)=.T.
		RUTAICO:=LEFT(RUTAPROGRAMA,RAT("\",RUTAPROGRAMA))+"Ico\"+NOMICO2
		EXIT
	CASE FILE(LEFT(RUTAPROGRAMA,AT("SUIZOWIN",UPPER(RUTAPROGRAMA))+7)+"\Ico\"+NOMICO2)=.T.
		RUTAICO:=LEFT(RUTAPROGRAMA,AT("SUIZOWIN",UPPER(RUTAPROGRAMA))+7)+"\Ico\"+NOMICO2
		EXIT
	CASE FILE("\SuizoWin\Ico\"+NOMICO2)=.T.
		RUTAICO:="\SuizoWin\Ico\"+NOMICO2
		EXIT
	ENDCASE
NEXT
IF LEN(RUTAICO)<=0
	RUTAICO:="Z"+NOMICO
ENDIF
RETURN(RUTAICO)
