* IMPLET1=NUMERO  IMPLETL=LETRA
FUNCTION NUMLET(IMPORTE,MONEDA)
LOCAL NUM2:=0
MONEDA:=IF(MONEDA=NIL,"MONEDA",MONEDA) //MONEDA O NUMERO
IMPLET1:=PADL(LTRIM(STR(INT(IMPORTE))),12," ")

IMPORTD:=(IMPORTE-INT(IMPORTE))*100
IMPORTD:=STR(IMPORTD)
IMPORTD:=LEFT(IMPORTD,AT(".",IMPORTD)-1)
IMPLET2:=PADL(LTRIM(IMPORTD),3," ")

IMPLETL:=""

FOR N=1 TO 5
DO CASE
   CASE N=1
      IF SUBSTR(IMPLET1,3,1)<>" "
         IMPLETL:=IMPLETL+NUMLETM(VAL(SUBSTR(IMPLET1,1,3)))
      ELSE
         LOOP
      ENDIF
   CASE N=2
      IF SUBSTR(IMPLET1,3,1)<>" "
         IMPLETL:=IMPLETL+" mil"
      ENDIF
      IF SUBSTR(IMPLET1,6,1)<>" "
         IMPLETL:=IMPLETL+NUMLETM(VAL(SUBSTR(IMPLET1,4,3)))
      ELSE
         LOOP
      ENDIF
   CASE N=3
      IF SUBSTR(IMPLET1,6,1)<>" "
         IMPLETL:=IMPLETL+" millones"
      ENDIF
      IF SUBSTR(IMPLET1,9,1)<>" "
         IMPLETL:=IMPLETL+NUMLETM(VAL(SUBSTR(IMPLET1,7,3)))
      ELSE
         LOOP
      ENDIF
   CASE N=4
      IF SUBSTR(IMPLET1,9,1)<>" " .AND. SUBSTR(IMPLET1,7,3)<>"000"
         IMPLETL:=IMPLETL+" mil"
      ENDIF
      IMPLETL:=IMPLETL+NUMLETM(VAL(SUBSTR(IMPLET1,10,3)))
      IF MONEDA="MONEDA"
         IMPLETL:=IMPLETL+" "+LOWER(RTRIM(MDA_NOM2(EJERANY)))
      ENDIF
   CASE N=5 //DECIMALES
      IF SUBSTR(IMPLET2,3,1)<>" " .AND. IMPLET2<>"  0"
         IMPLETL:=IMPLETL+" con"+NUMLETM(VAL(SUBSTR(IMPLET2,1,3)))
         IF MONEDA="MONEDA"
            IF IMPLET2="  1"
               IMPLETL:=IMPLETL+" centimo"
            ELSE
               IMPLETL:=IMPLETL+" centimos"
            ENDIF
         ENDIF
      ELSE
         LOOP
      ENDIF
ENDCASE
NEXT
IMPLETL:=ALLTRIM(IMPLETL)
IMPLETL:=UPPER(LEFT(IMPLETL,1))+SUBSTR(IMPLETL,2,LEN(IMPLETL)-1)
RETURN(IMPLETL)



*
STATIC FUNCTION NUMLETM(IMP_MIL)
IMP_MIL:=PADL(LTRIM(STR(INT(IMP_MIL))),3," ")
IMP_NOM:=""
DO CASE
   CASE LEFT(IMP_MIL,1)="1"
      IF RIGHT(IMP_MIL,2)<>"00"
         IMP_NOM=IMP_NOM+" ciento"
      ELSE
         IMP_NOM=IMP_NOM+" cien"
      ENDIF
   CASE LEFT(IMP_MIL,1)="2"
      IMP_NOM=IMP_NOM+IF(MDA_NOM1(EJERANY)="EURO"," doscientos"," doscientas")
   CASE LEFT(IMP_MIL,1)="3"
      IMP_NOM=IMP_NOM+IF(MDA_NOM1(EJERANY)="EURO"," trescientos"," trescientas")
   CASE LEFT(IMP_MIL,1)="4"
      IMP_NOM=IMP_NOM+IF(MDA_NOM1(EJERANY)="EURO"," cuatrocientos"," cuatrocientas")
   CASE LEFT(IMP_MIL,1)="5"
      IMP_NOM=IMP_NOM+IF(MDA_NOM1(EJERANY)="EURO"," quinientos"," quinientas")
   CASE LEFT(IMP_MIL,1)="6"
      IMP_NOM=IMP_NOM+IF(MDA_NOM1(EJERANY)="EURO"," seiscientos"," seiscientas")
   CASE LEFT(IMP_MIL,1)="7"
      IMP_NOM=IMP_NOM+IF(MDA_NOM1(EJERANY)="EURO"," setecientos"," setecientas")
   CASE LEFT(IMP_MIL,1)="8"
      IMP_NOM=IMP_NOM+IF(MDA_NOM1(EJERANY)="EURO"," ochocientos"," ochocientas")
   CASE LEFT(IMP_MIL,1)="9"
      IMP_NOM=IMP_NOM+IF(MDA_NOM1(EJERANY)="EURO"," novecientos"," novecientas")
ENDCASE
DO CASE
   CASE SUBSTR(IMP_MIL,2,1)="2"
      IF RIGHT(IMP_MIL,1)<>"0"
         IMP_NOM=IMP_NOM+" veinti"
      ELSE
         IMP_NOM=IMP_NOM+" veinte"
      ENDIF
   CASE SUBSTR(IMP_MIL,2,1)="3"
      IMP_NOM=IMP_NOM+" treinta"
   CASE SUBSTR(IMP_MIL,2,1)="4"
      IMP_NOM=IMP_NOM+" cuarenta"
   CASE SUBSTR(IMP_MIL,2,1)="5"
      IMP_NOM=IMP_NOM+" cincuenta"
   CASE SUBSTR(IMP_MIL,2,1)="6"
      IMP_NOM=IMP_NOM+" sesenta"
   CASE SUBSTR(IMP_MIL,2,1)="7"
      IMP_NOM=IMP_NOM+" setenta"
   CASE SUBSTR(IMP_MIL,2,1)="8"
      IMP_NOM=IMP_NOM+" ochenta"
   CASE SUBSTR(IMP_MIL,2,1)="9"
      IMP_NOM=IMP_NOM+" noventa"
ENDCASE
IF VAL(SUBSTR(IMP_MIL,2,1))>2 .AND. SUBSTR(IMP_MIL,3,1)<>"0"
  IMP_NOM=IMP_NOM+" y "
ENDIF
IF SUBSTR(IMP_MIL,2,1)="0"
  IMP_NOM=IMP_NOM+" "
ENDIF
DO CASE
   CASE SUBSTR(IMP_MIL,2,2)="10"
      IMP_NOM=IMP_NOM+" diez"
   CASE SUBSTR(IMP_MIL,2,2)="11"
      IMP_NOM=IMP_NOM+" once"
   CASE SUBSTR(IMP_MIL,2,2)="12"
      IMP_NOM=IMP_NOM+" doce"
   CASE SUBSTR(IMP_MIL,2,2)="13"
      IMP_NOM=IMP_NOM+" trece"
   CASE SUBSTR(IMP_MIL,2,2)="14"
      IMP_NOM=IMP_NOM+" catorce"
   CASE SUBSTR(IMP_MIL,2,2)="15"
      IMP_NOM=IMP_NOM+" quince"
   CASE SUBSTR(IMP_MIL,2,2)="16"
      IMP_NOM=IMP_NOM+" dieciseis"
   CASE SUBSTR(IMP_MIL,2,2)="17"
      IMP_NOM=IMP_NOM+" diecisiete"
   CASE SUBSTR(IMP_MIL,2,2)="18"
      IMP_NOM=IMP_NOM+" dieciocho"
   CASE SUBSTR(IMP_MIL,2,2)="19"
      IMP_NOM=IMP_NOM+" diecinueve"
   CASE SUBSTR(IMP_MIL,3,1)="1"
      DO CASE
         CASE N=1
            IF IMP_MIL<>"  1"
               IMP_NOM=IMP_NOM+"un"
            ENDIF
         CASE N=2
            IMP_NOM=IMP_NOM+"un"
         CASE N=3
            IF IMP_MIL<>"  1" .AND. IMP_MIL<>"001"
               IMP_NOM=IMP_NOM+"un"
            ENDIF
         CASE N=4
            IMP_NOM=IMP_NOM+"uno"
         CASE N=5
            IMP_NOM=IMP_NOM+" un"
      ENDCASE
   CASE SUBSTR(IMP_MIL,3,1)="2"
      IMP_NOM=IMP_NOM+"dos"
   CASE SUBSTR(IMP_MIL,3,1)="3"
      IMP_NOM=IMP_NOM+"tres"
   CASE SUBSTR(IMP_MIL,3,1)="4"
      IMP_NOM=IMP_NOM+"cuatro"
   CASE SUBSTR(IMP_MIL,3,1)="5"
      IMP_NOM=IMP_NOM+"cinco"
   CASE SUBSTR(IMP_MIL,3,1)="6"
      IMP_NOM=IMP_NOM+"seis"
   CASE SUBSTR(IMP_MIL,3,1)="7"
      IMP_NOM=IMP_NOM+"siete"
   CASE SUBSTR(IMP_MIL,3,1)="8"
      IMP_NOM=IMP_NOM+"ocho"
   CASE SUBSTR(IMP_MIL,3,1)="9"
      IMP_NOM=IMP_NOM+"nueve"
ENDCASE
RETURN(IMP_NOM)


FUNCTION LetraExcel(nLETEXCEL)
   cLETEXCEL1:=""
   cLETEXCEL2:=""
   cLETEXCEL3:=""
   DO WHILE INT((nLETEXCEL-1)/(26*26))>0
      cLETEXCEL1:=cLETEXCEL1+"Z"
      nLETEXCEL:=nLETEXCEL-(26*26)
   ENDDO
   IF INT(nLETEXCEL/26)>0
      IF INT(nLETEXCEL/26)=nLETEXCEL/26
         IF INT(nLETEXCEL/26)>1
            cLETEXCEL2:=cLETEXCEL2+CHR(64+INT(nLETEXCEL/26)-1)
            nLETEXCEL:=nLETEXCEL-((INT(nLETEXCEL/26)-1)*26)
         ENDIF
      ELSE
         cLETEXCEL2:=cLETEXCEL2+CHR(64+INT(nLETEXCEL/26))
         nLETEXCEL:=nLETEXCEL-(INT(nLETEXCEL/26)*26)
      ENDIF
   ENDIF
   IF nLETEXCEL>0
      cLETEXCEL3:=cLETEXCEL3+CHR(64+nLETEXCEL)
   ENDIF
   cLETEXCEL:=cLETEXCEL1+cLETEXCEL2+cLETEXCEL3
RETURN(cLETEXCEL)


FUNCTION LetraExceln(cLETEXCEL)
cLETEXCEL:=UPPER(cLETEXCEL)
cLETEXCEL2:=""
FOR N=1 TO LEN(cLETEXCEL)
   IF ISALPHA(SUBSTR(cLETEXCEL,N,1))=.T.
      cLETEXCEL2:=cLETEXCEL2+SUBSTR(cLETEXCEL,N,1)
   ELSE
      EXIT
   ENDIF
NEXT
nLETEXCEL:=0
FOR N=1 TO LEN(cLETEXCEL2)
   IF N=LEN(cLETEXCEL2)
      nLETEXCEL:=nLETEXCEL + ASC(SUBSTR(cLETEXCEL,N,1))-64
   ELSE
      nLETEXCEL:=nLETEXCEL + ( (ASC(SUBSTR(cLETEXCEL,N,1))-64) * 26 )
   ENDIF
NEXT
RETURN(nLETEXCEL)


FUNCTION SoloNumero(nSNUMERO1)
   nSNUMERO2:=""
   FOR ESN2=1 TO LEN(nSNUMERO1)
      IF ISDIGIT(SUBSTR(nSNUMERO1,ESN2,1))
         nSNUMERO2:=nSNUMERO2+SUBSTR(nSNUMERO1,ESN2,1)
      ENDIF
   NEXT
RETURN(nSNUMERO2)
