FUNCTION Suizo_saldocuenta(SP_CTA2,SP_DEBE2,SP_HABER2)
   IF SP_CTA2=0
      RETURN
   ENDIF

   NUMSEL2:=SELEC()
   ESTOY2:=RECNO()
   SELEC CUENTAS
   ORDCUE2:=INDEXORD()
   DBSETORDER(1)

   SEEK SP_CTA2
   IF EOF()
      APPEND BLANK
      IF RLOCK()
         REPLACE CODCTA WITH SP_CTA2
         REPLACE NOMCTA WITH "Alta "+Nombre_Programa()
         DBCOMMIT()
         DBUNLOCK()
      ENDIF
   ENDIF

   IF RLOCK()
      REPLACE SALDO WITH SALDO+SP_DEBE2-SP_HABER2
      DBCOMMIT()
      DBUNLOCK()
   ENDIF

   DBSETORDER(ORDCUE2)
   SELEC(NUMSEL2)
   GO ESTOY2

RETURN
