call \MisProg\QAC\QAC \SUIZOWIN\SuiConta\SuiContax.qac -BUILD -EXIT

IF EXIST \SUIZOWIN.GAT\SUICONTA\SUICONTA.EXE (
   COPY SUICONTA.EXE \SUIZOWIN.GAT\SUICONTA
   ) 
IF EXIST \SUIZOWIN.RED\SUICONTA\SUICONTA.EXE (
   COPY SUICONTA.EXE \SUIZOWIN.RED\SUICONTA
   ) 
IF EXIST \SUIZOWIN.ET\SUICONTA\SUICONTA.EXE (
   COPY SUICONTA.EXE \SUIZOWIN.ET\SUICONTA
   )
IF EXIST \SUIZOWIN.TEY\SUICONTA\SUICONTA.EXE (
   COPY SUICONTA.EXE \SUIZOWIN.TEY\SUICONTA
   )

DEL SUICONTA.EXE

